import Footer from "@/components/Footer";
import "./globals.css";
import SearchHeader from "@/components/SearchHeader";

export const metadata = {
  title: "Google clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div>
      {children}
      {/* Footer */}
      <Footer />
    </div>
  );
}
